# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  pack:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - run: mkdir lambda-content
    - run: cp -r ./actions lambda-content/actions
    - run: cp -r ./lib lambda-content/lib
    - run: cp ./lambda-handler.js lambda-content/lambda-handler.js
    - run: cp ./package.json lambda-content/package.json
    - run: zip -r meatbot.zip lambda-content
    - run: echo "zip created!"
    - run: rm -rf lambda-content 
